# .github/workflows/invoke-generate-toc.yml
# Restricted only to the main branch and README.md file.
---

name: Invoke Shared Generate TOC Workflow

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  toc:
    uses: apaivinen/shared-workflows/.github/workflows/generate-toc.yml@main
    with:
      target_file: README.md
