# .github/workflows/invoke-lint-markdown.yml in consumer repo
---

name: Invoke Shared Lint Markdown Workflow

on:
  pull_request:
    paths:
      - "**/*.md"
  workflow_dispatch:

jobs:
  lint:
    uses: apaivinen/shared-workflows/.github/workflows/lint-markdown.yml@main
    with:
      markdown_globs: "**/*.md"
